Demo/accounts/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path('register/', views.register ,name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('user_profile/', views.user_profile, name="user_profile"),
]

Demo/test_yourself/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="home"),
    path('about/', views.about, name="about_us"),
    path('catagory_exercise/<cat>/', views.catagory_exercise, name="catagories"),
    path('catagory_chapter/<cat>/<subcatagory>/', views.catagory_chapter, name="catagories_chapters"),
    path('test/<cat>/<subcat>/', views.test, name="test"),
    path('quiz/<cat>/<subcat>/', views.checkquestion, name="quiz"),
    path('get_comments/', views.get_comments, name="getting_comments")
]

Demo/web_application/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('', include('test_yourself.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    url(r'^friendship/', include('friendship.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Demo/test_yourself/models.py
from django.db import models
from django.contrib.auth.models import User
import re
from django.utils.translation import ugettext as _
from model_utils.managers import InheritanceManager
import os

# Create your models here.

class UserProfile(models.Model):
    user   = models.OneToOneField(User,on_delete=models.CASCADE)
    ProfilePhoto = models.ImageField(upload_to='User_Profiles')

    def __str__(self):
        return self.user.email

    def extension(self):
        name, extension = os.path.splitext(self.ProfilePhoto.name)
        return extension



class CategoryManager(models.Manager):

    def new_category(self, category):
        new_category = self.create(category=re.sub('\s+', '-', category)
                                   .lower())

        new_category.save()
        return new_category


class Category(models.Model):

    category = models.CharField(
        verbose_name=_("Category"),
        max_length=250, blank=True,
        unique=True, null=True)
    catagory_image = models.ImageField(upload_to='Catagories')
    catagory_explanation = models.TextField(max_length=2000,
                                            blank=True,
                                            help_text=_("Explanation to be shown "
                                                        "For the Catagory "),
                                            verbose_name=_('Catagory Explanation'))


    objects = CategoryManager()

    class Meta:
        verbose_name =_("Category")
        verbose_name_plural = ("Categories")

    def __str__(self):
        return self.category

class SubcatManager(models.Manager):

    def new_subcat(self, subcat):
        new_subcat = self.create(subcat=re.sub('\s+', '-', subcat)
                                   .lower())

        new_subcat.save()
        return new_subcat

class Subcat(models.Model):
    catag = models.ForeignKey(Category,
                              verbose_name=_("Catagory"),
                              blank=True,
                              null=True, on_delete= models.CASCADE)
    subcat = models.CharField(
        verbose_name=_("Sub category"),
        max_length=250, blank=True,
        unique=True, null=True)


    objects = SubcatManager()

    class Meta:
        verbose_name = _("Sub category")
        verbose_name_plural = _("Sub categories")

    def __str__(self):
        return self.subcat





class Question(models.Model):
    """
    Base class for all question types.
    Shared properties placed here.
    """


    category = models.ForeignKey(Category,
                                 verbose_name=_("Category"),
                                 blank=True,
                                 null=True, on_delete=models.CASCADE)
    subcat = models.ForeignKey(Subcat,
                              verbose_name=('Sub category'),
                               null=True, on_delete=models.CASCADE)


    content = models.CharField(max_length=1000,
                               blank=False,
                               help_text=_("Enter the question text that "
                                           "you want displayed"),
                               verbose_name=_('Question'))

    explanation = models.TextField(max_length=2000,
                                   blank=True,
                                   help_text=_("Explanation to be shown "
                                               "after the question has "
                                               "been answered."),
                                   verbose_name=_('Explanation'))

    objects = InheritanceManager()

    class Meta:
        verbose_name = _("Question")
        verbose_name_plural = _("Questions")
        ordering = ['category']

    def __str__(self):
        return self.content


class MCQQuestion(Question):


    def check_if_correct(self, guess):
        answer = Answer.objects.get(id=guess)

        if answer.correct is True:
            return True
        else:
            return False


    def get_answers_list(self):
        return [(answer.id, answer.content) for answer in self.order_answers(Answer.objects.filter(question=self))]

    def answer_choice_to_string(self, guess):
        return Answer.objects.get(id=guess).content

    class Meta:
        verbose_name = "Multiple Choice Question"
        verbose_name_plural = "Multiple Choice Questions"


class Answer(models.Model):
    question = models.ForeignKey(MCQQuestion, verbose_name='Question', on_delete=models.CASCADE)

    content = models.CharField(max_length=1000,
                               blank=False,
                               help_text="Enter the answer text that \
                                            you want displayed",
                               verbose_name="Content")

    correct = models.BooleanField(blank=False,
                                  default=False,
                                  help_text="Is this a correct answer?",
                                  verbose_name="Correct")

    def __str__(self):
        return self.content


    class Meta:
        verbose_name = "Answer"
        verbose_name_plural = "Answers"


class Comment(models.Model):
    question = models.ForeignKey(MCQQuestion,verbose_name='Comment_of_Question',on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    reply = models.ForeignKey("Comment", null=True, blank=True, related_name="replies", on_delete=models.CASCADE)
    content = models.TextField(max_length=160)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} Commented on {}'.format(str(self.user.username), self.question)

Demo/test_yourself/views.py
from django.shortcuts import render
from .models import MCQQuestion,Category,Subcat,Comment
from django.http import JsonResponse
from django.core import serializers

# Create your views here.
def index(request):
    cat = Category.objects.all()
    return render(request, 'test_yourself/index.html', {'catags': cat})

def about(request):
    return render(request,'test_yourself/about.html')

def catagory_exercise(request,cat):
    catag = Category.objects.get(category = cat)
    subcat = Subcat.objects.filter(catag=catag)
    Qu = MCQQuestion.objects.filter(category = catag)
    qc = MCQQuestion.objects.all()[:1].get()
    Comments = Comment.objects.filter(question = qc).order_by('-id')
    #for comment in Comments:
    #    print(comment)

    params = {
        'Qu': Qu,
        'catagory' : catag,
        'subcat' : subcat,
        'comments': Comments
    }
    return render(request, 'test_yourself/catagories.html', params)

def get_comments(request):
    qi = request.POST['mcq']
    Qu = MCQQuestion.objects.get(content=qi)
    Comments = Comment.objects.filter(question = Qu)
    comments_serialized = serializers.serialize('json', Comments)
    return JsonResponse(comments_serialized,safe=False)

def catagory_chapter(request,cat,subcatagory):
    catag = Category.objects.get(category = cat)
    subcatagories = Subcat.objects.filter(catag = catag)
    subcatag = Subcat.objects.get(subcat = subcatagory)
    Qu = MCQQuestion.objects.filter(category = catag,subcat = subcatag)
    params = {
        'Qu': Qu,
        'catagory' : catag,
        'subcat' : subcatagories,
        'subcatag' : subcatag
    }
    return render(request, 'test_yourself/catagories.html', params)

def test(request,cat,subcat):
    catag = Category.objects.get(category = cat)
    subcatag = Subcat.objects.get(subcat = subcat)
    Qu = MCQQuestion.objects.filter(category = catag, subcat = subcatag).order_by('?')[:20]
    params = {
        'Qu': Qu,
        'catagory' : catag,
        'subcatagory' : subcatag
    }
    return render(request, 'test_yourself/test.html', params)

def checkquestion(request,cat,subcat):
    answ = []
    correct_ans = []
    score = 0
    for radio_answer in [key for key in request.POST.keys() if key.startswith('answers[')]:
        answ.append(radio_answer)
    for correct_answers in [key for key in request.POST.keys() if key.startswith('correct_answer[')]:
        correct_ans.append(correct_answers)

    selectans = []
    rightans = []

    for selec in answ:
        chk = request.POST[selec]
        selectans.append(chk)

    for right in correct_ans:
        get = request.POST[right]
        rightans.append(get)

    for check in range(0,len(answ)):
        if selectans[check] == rightans[check]:
            score = score + 1

    params = {
        'user_selected': selectans,
        'right_answer': rightans,
        'score' : score,
        'catagory' : cat,
        'subcatagory' : subcat
    }

    return render(request,'test_yourself/final_result.html', params)

Demo/templates/test_yourself/about.html
{% load static %}
{% static "img" as baseUrl %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *Must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>LetUsPrepareYou | Home</title>

    <!-- Favicon -->
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<body>
    <!-- Preloader -->
    <div id="preloader">
        <div class="spinner"></div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">

        <!-- Navbar Area -->
        <div class="clever-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <!-- Menu -->
                <nav class="classy-navbar justify-content-between" id="cleverNav">

                    <!-- Logo -->
                    <a class="nav-brand" href="/"><h3>Test Yourself</h3></a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">

                        <!-- Close Button -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->
                        <div class="classynav">
                            <ul style="padding-right: 300px;">
                                <li><a href="/">Home</a></li>
                                <li><a href="/about/">About Us</a></li>
                            </ul>

                            <!-- Register / Login / Logout-->

                            <div class="register-login-area">

                                {% if user.is_authenticated %}
                                
                                    <a href="/accounts/user_profile/"> <img src="{{ user.userprofile.ProfilePhoto.url }}" style="border-radius:50%;width:50px;height:50px;"> </a>
                                    <a href="/accounts/logout/">Logout</a>

                                {% else %}

                                    <a href="/accounts/register/" class="btn">Register</a>
                                    <a href="/accounts/login/" class="btn active">Login</a>

                                {% endif %}

                            </div>

                        </div>
                        <!-- Nav End -->
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->

    <!-- ##### Hero Area Start ##### -->
    <section class="hero-area bg-img bg-overlay-2by5" style="background-image: url({% static 'img/bg-img/bg1.jpg' %});">
        <div class="container h-100">
            <div class="row h-100 align-items-center">

                <div class="col-12">
                    <!-- Hero Content -->
                            {% if user.is_authenticated %}

                            <div class="hero-content text-center">
                                <h2>Let Us Prepare You</h2>
                                <a href="#" class="btn clever-btn">Welcome, Mr {{user.first_name}}  {{user.last_name}}</a>
                            </div>

                            {% else %}

                             <div class="hero-content text-center">
                                 <h2>Let Us Prepare You</h2>
                                 <a href="/accounts/register/" class="btn clever-btn">Register</a>
                             </div>

                            {% endif %}

                    </div>
            </div>
        </div>
    </section>
    <!-- ##### Hero Area End ##### -->

    <!-- ##### About Heading Start ##### -->
    <section class="popular-courses-area section-padding-100-0" style="background-image: url({% static 'img/core-img/texture.png' %});">
        <div class="container" style="padding-bottom:100px">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading">
                        <h3>A Few Words About Us</h3>
                    </div>
                </div>
            </div>


            <div class="card">
                <div class="card-body" style="text-align:Justify;font-size:20px">
                     We have Created This website For Helping Those Students Who Want to Learn and make Themselves Best Among People.<br><br>
                     By This Website You Can Learn and Test Yourself.
                    You Don't need of anyone to ask Question from you anymore..  We are Here to Do that for you. ☻<br><br>
                    This Website has 10 Practice Quiz's For Every Catagory of <strong>Test</strong>
                 </div>
            </div>

        </div>
    </section>
    <!-- ##### About Heading End ##### -->

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer-area">
        <!-- Top Footer Area -->
        <div class="top-footer-area">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Footer Logo -->
                        <div class="footer-logo">
                            <a href="index.html"><h3 style="color: #ffffff;">Let Us Prepare you</h3></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Bottom Footer Area -->
        <div class="bottom-footer-area d-flex justify-content-between align-items-center">
            <!-- Contact Info -->
            <div class="contact-info">
                <a href="https://www.facebook.com/mutaher.affan14"><span>Mutaher's Email:</span> Mutaher Affan</a>
                <a href="#"><span>Bilal's Email:</span> Ahmed Bilal</a>
            </div>
            <!-- Follow Us -->
            <div class="follow-us">
                <span>Follow us</span>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
</body>

</html>

Demo/templates/test_yourself/final_result.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>LetUsPrepareYou | Test</title>
  <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <a class="navbar-brand" href="#">Test Yourself</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/test/{{catagory}}/{{subcatagory}}">Start Quiz Again</a>
      </li>
    </ul>
  </div>
</nav>
<br>

    <!-- ##### MCQS Heading Start ##### -->
    <section class="popular-courses-area section-padding-100-0" style="background-image: url({% static 'img/core-img/texture.png' %});">
        <div class="container" style="padding-bottom:100px">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading row align-items-center justify-content-center">
                        <h2>Final Result</h2>
                    </div>
                </div>
            </div>
    <!-- ##### MCQS Heading End ##### -->

    <!-- #### MCQS GETTING USING JINJA TEMPLATE START #### -->

            <div class="card" style="margin-top:40px;">
                <div class="card-body" style="font-size:20px;">
                    <div class="container-fluid" style="text-align:center;">
                        <div class="row">
                            <div class="col-lg-6">
                                <h4 style="padding-bottom:20px;">User Selected</h4>
                                {% for user in user_selected %}
                                <p style="color:red;">{{user}}<br></p>
                                {% endfor %}
                            </div>
                            <div class="col-lg-6">
                                <h4 style="padding-bottom:20px;">Correct Answers</h4>
                                {% for right in right_answer %}
                                <p style="color:green;">{{right}}<br></p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                 </div>
            </div>

            <!-- #### MCQS GETTING USING JINJA TEMPLATE END #### -->

        </div>
    </section>

            <h5 style="text-align:center;">You Score is : {{score}}</h5>
    <!-- ##### MCQS Heading End ##### -->

</body>
</html>

Demo/templates/test_yourself/test.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>LetUsPrepareYou | Test</title>
  <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


    <!-- ##### CHECKING IF SOME ONE IS CHEATING USING ANOTHER TAB ##### -->

  <script>

        // main visibility API function
        // use visibility API to check if current tab is active or not
        var vis = (function(){
        var stateKey,
        eventKey,
        keys = {
                hidden: "visibilitychange",
                webkitHidden: "webkitvisibilitychange",
                mozHidden: "mozvisibilitychange",
                msHidden: "msvisibilitychange"
        };
        for (stateKey in keys) {
            if (stateKey in document) {
                eventKey = keys[stateKey];
                break;
            }
        }
        return function(c) {
            if (c) document.addEventListener(eventKey, c);
            return !document[stateKey];
        }
    })();

        vis(function(){

            if(vis()){

                // tween resume() code goes here
	            setTimeout(function(){
                console.log("tab is visible - has focus");
                },300);

            } else {

                // tween pause() code goes here
                console.log("tab is invisible - has blur");
            }
        });

        // check if browser window has focus
        var notIE = (document.documentMode === undefined),
        isChromium = window.chrome;
        var chances = 3;

        if (notIE && !isChromium) {

            // checks for Firefox and other  NON IE Chrome versions
            $(window).on("focusin", function () {

                // tween resume() code goes here
                setTimeout(function(){
                console.log("focus");
                },300);

            }).on("focusout", function () {

            // tween pause() code goes here
            console.log("blur");

            });

        } else {

            // checks for IE and Chromium versions
            if (window.addEventListener) {

            // bind focus event
            window.addEventListener("focus", function (event) {

                // tween resume() code goes here
                setTimeout(function(){
                    console.log("focus");
                },300);

            }, false);

            // bind blur event
            window.addEventListener("blur", function (event) {

                // tween pause() code goes here
                // GIVING USERS 3 OPPORTUNITIES TO NOT TO GO TO ANOTHER TAB OR BROWSER BEFORE SUBMITTING ANSWERS
                //OTHERWISE TEST WILL BE CANCELED.

                chances = chances - 1;

                if(chances == 0){
                    window.close();
                    console.log(chances);
                }
                else if(chances == 1){
                    alert("Warning! You have gone out from Test 2 times,so this is last time")
                }
                console.log("blur");

            }, false);

        } else {

            // bind focus event
            window.attachEvent("focus", function (event) {

                // tween resume() code goes here
                setTimeout(function(){
                    console.log("focus");
                },300);

            });

            // bind focus event
            window.attachEvent("blur", function (event) {

                // tween pause() code goes here
                console.log("blur");

            });
        }
    }

  </script>


  <!-- ##### CHECKING ALL QUESTIONS HAS BEEN ANSWERED OR NOT ##### -->
  <script>
    $(document).ready(function(){
        $("#check").click(function(){
            var $ques = $(".questions");
            if($ques.find("input:radio:checked").length === $ques.length) {
                var $myForm = $('#submit');
                $myForm.submit(function(event){
                 event.preventDefault();
                 var $formData = $myForm.serialize();
                 var $thisURL = $myForm.attr('action') || window.location.href;
                 $.ajax({
                 method:'POST',
                 url: $thisURL,
                 data: $formData,
                 success: handleSuccess,
                 error: handleError,
                 });
                 function handleSuccess(data){
                 console.log(data);
                 $('html').html(data);
                 }
                 function handleError(ThrowError){
                 console.log(ThrowError)
                 }

                });
            }
            else {
                alert("Please Select an Answer from all Questions.");
                $("#submit").submit(function(e) {
                e.preventDefault();
                });
            }
        });
    });
</script>

</head>
<body>

<nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
  <a class="navbar-brand" href="#">Test Yourself</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="javascript:window.close();">Close Quiz</a>
      </li>
    </ul>
  </div>
</nav>
<br>

    <!-- ##### MCQS Heading Start ##### -->
    <section class="popular-courses-area section-padding-100-0" style="background-image: url({% static 'img/core-img/texture.png' %});">
        <div class="container" style="padding-bottom:100px">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading row align-items-center justify-content-center">
                        <h5># {{subcatagory}} Test</h5>
                    </div>
                </div>
            </div>
    <!-- ##### MCQS Heading End ##### -->

    <!-- #### MCQS GETTING USING JINJA TEMPLATE START #### -->

            <div class="card" style="margin-top:40px;">
                <div class="card-body" style="font-size:20px;">

                    <form action="/quiz/{{catagory}}/{{subcatagory}}/" id="submit" method="post">

					{% csrf_token %}

                    {% for mcq in  Qu %}
                        <div class="questions">
                        <strong>{{forloop.counter}}. {{mcq.content}}</strong>

                        <ul class="list-group" style="margin-top:20px;">

                        {% for ans in mcq.answer_set.all %}

                            <li class="list-group-item d-flex justify-content-between align-items-center">

                                <h6 style="float:right;font-size:20px"> <small>
                                    <span class="badge badge-primary" style="float:left;margin-right:20px;">{{forloop.counter}}</span>
                                    <!-- Material unchecked -->
                                    <div class="form-check" style="padding-left:60px;">
                                    <input type="radio" class="form-check-input" id="answer[{{ ans.content }}]" name="answers[{{ mcq.id }}]" value="{{ ans.content }}">
                                    <label class="form-check-label" for="answer[{{ ans.content }}]">{{ ans.content }}</label>
                                    </div>
                                </small> </h6>

                            </li>

                        {% endfor %} <br>

                        </ul>


                        {% for ans in mcq.answer_set.all %}
                            {% if ans.correct is True %}
                                <input type="hidden" value="{{ ans.content }}" name="correct_answer[{{ ans }}]">
                            {% endif %}
                        {% endfor %}


                    {% endfor %}
                            </div>

                        <button type="submit" class="btn btn-primary" id="check">
                            Submit Answers ☻
                        </button>


                    </form>

                 </div>
            </div>

            <!-- #### MCQS GETTING USING JINJA TEMPLATE END #### -->

        </div>
    </section>
    <!-- ##### MCQS Heading End ##### -->

</body>
</html>